on:
  push:
      tags:
        - '*'
name: Test, Release Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.7.8+hotfix.4'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --flavor prodgithub  --release
    - run: echo $KEY_JKS > key.jks
    - name: Build
      run: flutter build apk --flavor prodgithub --release
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: build/app/outputs/apk/prodgithub/release
        signingKeyBase64: ${{ secrets.KEY_JKS }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_PASSWORD }}
        keyPassword: ${{ secrets.ALIAS_PASSWORD }}
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/prodgithub/release/*.apk"
        token: ${{ secrets.TOKEN }}

